title: NING QU's Homepage
page-top-title: 渠宁
top-section-bg-text: Be what you wanna be
home-subtitle: NING QU&ensp;|&ensp;渠宁
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
site_name: 渠宁(QU NING)
email: stillqu@stu.xjtu.edu.cn